name: Publish release
 
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write 

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
      - name: Publish to NPM
        run: |
          yarn push 
